/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Upload } from "./Upload";
export * as factories from "./factories";
export { Upload__factory } from "./factories/Upload__factory";
